### ISSUE TITLE
PHPUnit dependencies problems

### ISSUE THREAD

**Issue by peter279k** [Xethron/bignum#1]
As title. It's about the PHPUnit dependency problems.

According to the official [PHPUnit reference](https://phpunit.de/announcements/phpunit-7.html), the PHPUnit required `php-7.1` version, but this package requires `php-7.0` version at least.

I suggest we should let this package require `php-7.1` version at least.

We can look at [composer.json](https://github.com/Xethron/bignum/blob/master/composer.json#L6) in `require` and `require-dev` blocks.

**Comment by Xethron** [comment]
This should be fixed in the latest update.
